# Generated by Django 5.0.6 on 2024-06-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed')], default='available', max_length=10),
        ),
    ]
